server:
  port: 8090

spring:
  datasource:
    username: root
    password: buaase2020.
    url: jdbc:mysql://123.56.145.79:3306/document?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: -1

mybatis:
  type-aliases-package: com.document.pojo
  mapper-locations: classpath:mapper/*.xml
